### ISSUE TITLE
adding attribute support

### ISSUE THREAD

**Issue by lavaner** [caiofcm/filter_pandoc_run_py#5]
since fignos filter can auto numbering figs by a attribute block{#fig:}, so I was wondering if we can adding a  key something like 'attribute'. 

the syntax would be like 

[{.python .run format=[blockquote (default), text] hide_code=[False (default), True] } caption="Caption" attribute="#fig:id"]

with attribute added, the return ast code should be change into

\!\[Caption\](filePath){#fig:id}

and that is work well with fignos.

even fignos filter is not enabled, adding a attribute seems harmless.

**Comment by caiofcm** [comment]
Yes, that would help a lot. Thank you

**Comment by kiwi0fruit** [comment]
Why fignos instead of pandoc-crossref?

**Comment by caiofcm** [comment]
You can now use:

```
```{.python .run caption="A Figure" caption2="Other Figure " figattr="#fig:2 width=8in" figattr2="#fig:3 width=3in tag='B.1'"}
```
